// aivideo-web-react/src/pages/ai/setting/index.tsx
import { useMutation, useQuery } from '@tanstack/react-query';
import { Button, Card, Space, Table, Popconfirm, message, Modal } from 'antd';
import { ColumnsType } from 'antd/es/table';
import { TableRowSelection } from 'antd/es/table/interface';
import { useState } from 'react';
import { styled } from 'styled-components';

import aiService, { DeviceItem, RuleItem } from '@/api/services/aiService';

import AddRulePage from './add-rule';
import { notificateTypeOptions } from './base-set';
import EditDeviceRulePage from './edit-device-rule';
import EditRulePage from './edit-rule';

export interface ExpandColumns extends DeviceItem {
  ruleId: number;
}

export type RuleListProps = {
  alarmTypeId: string;
  title: string;
};

export default function RuleList({ alarmTypeId, title }: RuleListProps) {
  // const [searchForm] = Form.useForm();
  const [actionType, setActionType] = useState('list');
  const [currentRuleID, setCurrentRuleID] = useState<number>(0);
  const [queryParams, setQueryParams] = useState({
    page: 1,
    pageSize: 10,
    query: undefined,
    alarmTypeId, // 模型ID
  });

  const [selectedRows, setSelectedRows] = useState<RuleItem[]>([]);
  const selectedRowKeys = selectedRows.map((item) => item.id);

  const columns: ColumnsType<RuleItem> = [
    {
      title: '序号',
      dataIndex: 'id',
      width: 50,
      render: (_value, _record, index) => index + 1 + (queryParams.page - 1) * queryParams.pageSize,
    },
    {
      title: '设备名称',
      dataIndex: 'device',
      render: (_text, record) => record?.device?.length && record.device[0].name,
    },
    {
      title: '设备ID',
      dataIndex: 'device',
      render: (_text, record) => record?.device?.length && record.device[0].channelId,
    },
    {
      title: '通知方式',
      dataIndex: 'notificateType',
      width: 100,
      render: (_text, record) => {
        if (record?.notificateType?.length) {
          return record.notificateType
            .map((item) => notificateTypeOptions.find((i) => i.value === item)?.label)
            .join(',');
        }
        return '无';
      },
    },
    {
      title: '通知人员',
      dataIndex: 'notificatePeople',
      width: 100,
      render: (_text, record) => {
        if (record?.notificatePeople?.length) {
          return record.notificatePeople.map((item) => item.name).join(' , ');
        }
        return '无';
      },
    },
    {
      title: '操作',
      key: 'operation',
      align: 'center',
      width: 100,
      render: (_, record) => (
        <div className="flex justify-center w-full text-gray">
          <Button type="link" onClick={() => handleEditRule(record)}>
            编辑
          </Button>
          <Popconfirm
            title="确定要删除该设备吗"
            okText="确认"
            cancelText="取消"
            placement="left"
            onConfirm={() => handleDeleteRule(record.id)}
          >
            <Button type="link" danger loading={batchDeleteLoading || deleteLoading}>
              删除
            </Button>
          </Popconfirm>
        </div>
      ),
    },
  ];

  const rowSelection: TableRowSelection<RuleItem> = {
    selectedRowKeys,
    onSelect: (record, selected) => {
      if (selected) {
        // 选中
        setSelectedRows([...selectedRows, record]);
      } else {
        // 取消选中
        setSelectedRows(selectedRows.filter((item) => item.id !== record.id));
      }
    },
    onSelectAll: (selected, _selectedRows, changeRows) => {
      if (selected) {
        // 选中
        setSelectedRows([...selectedRows, ...changeRows]);
      } else {
        // 取消选中
        const list = selectedRows.filter(
          (item) => !changeRows.some((changeRow) => changeRow.id === item.id),
        );
        setSelectedRows(list);
      }
    },
  };

  const { data, isLoading, refetch } = useQuery({
    queryKey: ['getRuleListByAlarmType', queryParams],
    queryFn: () => aiService.getRuleListByAlarmType(queryParams),
    onSuccess: (data) => {
      setSelectedRows([]);
      console.log(data);
    },
  });

  const { isLoading: deleteLoading, mutate: deleteRule } = useMutation(
    aiService.deteleRuleByAlarmType,
    {
      onSuccess: () => {
        message.success('删除规则成功');
        // 更新查询接口数据
        refetch();
      },
    },
  );

  const { isLoading: batchDeleteLoading, mutate: batchDeleteRule } = useMutation(
    aiService.batchdeteleRule,
    {
      onSuccess: () => {
        message.success('批量删除规则成功');
        // 更新查询接口数据
        refetch();
      },
    },
  );

  // const onSearchFormReset = () => {
  //   searchForm.resetFields();
  // };

  // const onSearchFormSubmit = () => {
  //   setQueryParams((prev) => {
  //     const date = searchForm.getFieldsValue();
  //     return { ...prev, ...date };
  //   });
  // };

  const pageChange = (page: number, pageSize: number) => {
    setQueryParams({ ...queryParams, page, pageSize });
  };

  const handleCreatRule = () => {
    setActionType('add');
  };

  const handleEditRule = (record: RuleItem) => {
    setActionType('edit');
    setCurrentRuleID(record.id);
  };

  const handleBetchEditRule = () => {
    if (selectedRowKeys.length < 2) {
      message.warning('请至少选择2条要编辑的规则');
      return;
    }
    const instance = Modal.confirm({
      title: '批量设置',
      content: (
        <>
          <p>
            是否批量设置<span className="font-bold text-error">{selectedRowKeys.length}</span>
            条规则？
          </p>
          <p className="font-bold text-error">已选中的规则会被覆盖为新的规则。</p>
        </>
      ),
      maskClosable: true,
      onOk: () => {
        setActionType('editDevice');
        instance.destroy();
      },
    });
  };

  const handleDeleteRule = (ruleId: number) => {
    deleteRule({ ruleId });
  };

  const handleBetchDelete = () => {
    if (selectedRowKeys.length < 2) {
      message.warning('请至少选择2条要删除的规则');
      return;
    }
    const instance = Modal.confirm({
      title: '批量删除',
      content: (
        <>
          <p>
            是否批量删除<span className="font-bold text-error">{selectedRowKeys.length}</span>
            条规则？
          </p>
          <p className="font-bold text-error">删除后不可恢复!</p>
        </>
      ),
      maskClosable: true,
      onOk: () => {
        batchDeleteRule(selectedRowKeys);
        instance.destroy();
      },
    });
  };

  return (
    <Space direction="vertical" size="large" className="w-full">
      {actionType === 'list' && (
        <>
          {/* <Card>
            <Form form={searchForm}>
              <Row gutter={[16, 16]}>
                <Col span={12} lg={8}>
                  <Form.Item<GetRuleListByAlarmTypeReq>
                    label="设备名称"
                    name="query"
                    className="!mb-0"
                  >
                    <Input placeholder="请输入设备名称" allowClear />
                  </Form.Item>
                </Col>
                <Col span={12} lg={6}>
                  <div className="flex">
                    <Button onClick={onSearchFormReset}>重置</Button>
                    <Button type="primary" className="ml-4" onClick={onSearchFormSubmit}>
                      搜索
                    </Button>
                  </div>
                </Col>
              </Row>
            </Form>
          </Card> */}
          <Card
            title={title}
            loading={isLoading}
            extra={
              <Space>
                <Button type="primary" className="ml-4" onClick={handleCreatRule}>
                  新增规则
                </Button>
                <Button
                  className="ml-4"
                  style={{ color: 'red', borderColor: 'red' }}
                  onClick={handleBetchEditRule}
                >
                  批量配置
                </Button>
                <Button type="primary" danger className="ml-4" onClick={handleBetchDelete}>
                  批量删除
                </Button>
              </Space>
            }
          >
            <StyledTable>
              <Table
                loading={deleteLoading || batchDeleteLoading}
                rowKey="id"
                size="small"
                scroll={{ x: 'max-content' }}
                pagination={{
                  defaultPageSize: queryParams.pageSize,
                  current: queryParams.page,
                  total: data?.total || 0,
                  onChange: pageChange,
                  pageSizeOptions: [10, 20, 40, 100],
                }}
                columns={columns}
                dataSource={data?.list}
                rowSelection={{ ...rowSelection }}
              />
            </StyledTable>
          </Card>
        </>
      )}
      {actionType === 'add' && (
        <AddRulePage alarmTypeId={alarmTypeId} setActionType={setActionType} />
      )}

      {actionType === 'edit' && (
        <EditRulePage
          alarmTypeId={alarmTypeId}
          setActionType={setActionType}
          ruleId={currentRuleID}
        />
      )}
      {actionType === 'editDevice' && (
        <EditDeviceRulePage
          selectedRows={selectedRows}
          alarmTypeId={alarmTypeId}
          setActionType={setActionType}
        />
      )}
    </Space>
  );
}

const StyledTable = styled.div`
  background: #fff;
  height: 100%;

  .ant-table-wrapper tr.ant-table-expanded-row > td {
    background: #fff;
  }

  .ant-table-wrapper tr.ant-table-expanded-row:hover > td {
    background: none;
  }

  /* .ant-table-wrapper
    .ant-table.ant-table-small
    .ant-table-tbody
    .ant-table-wrapper:only-child
    .ant-table {
    margin-inline: 0px;
  } */
`;

// aivideo-gat1400/src/views/ai/setting/index.vue
<template>
  <div class="app-container ai-setting-page">
    <template v-if="actionType === 'list'">
      <el-card shadow="never">
        <template #header>
          <div class="card-header">
            <span>算法配置</span>
            <el-space>
              <el-button type="primary" :disabled="!activeCategory" @click="actionType = 'add'">新增规则</el-button>
              <el-button type="warning" :disabled="selectedRows.length < 2" @click="batchEdit">批量配置</el-button>
              <el-button type="danger" :disabled="selectedRows.length < 2" @click="batchRemove">批量删除</el-button>
            </el-space>
          </div>
        </template>

        <el-tabs v-if="categories.length" v-model="activeAlarmTypeId" @tab-change="changeCategory">
          <el-tab-pane
            v-for="item in categories"
            :key="String(item.alarmTypeId || item.id)"
            :name="String(item.alarmTypeId || item.id)"
            :label="item.alarmTypeName"
          />
        </el-tabs>
        <el-empty v-else description="暂无启用算法，请先在算法库启用算法" />

        <el-form v-if="categories.length" :model="queryParams" inline class="mb12">
          <el-form-item label="设备名称">
            <el-input
              v-model="queryParams.query"
              clearable
              placeholder="请输入设备名称"
              style="width: 220px"
              @keyup.enter="handleQuery"
            />
          </el-form-item>
          <el-form-item>
            <el-button type="primary" icon="Search" @click="handleQuery">搜索</el-button>
            <el-button icon="Refresh" @click="resetQuery">重置</el-button>
          </el-form-item>
        </el-form>

        <el-table
          v-if="categories.length"
          v-loading="loading || deleteLoading"
          :data="tableData"
          row-key="id"
          border
          @selection-change="handleSelectionChange"
        >
          <el-table-column type="selection" width="50" />
          <el-table-column label="序号" type="index" width="70" align="center" />
          <el-table-column label="设备名称" min-width="160" show-overflow-tooltip>
            <template #default="{ row }">{{ firstDevice(row)?.name || '-' }}</template>
          </el-table-column>
          <el-table-column label="设备ID" min-width="160" show-overflow-tooltip>
            <template #default="{ row }">{{ firstDevice(row)?.channelId || firstDevice(row)?.deviceId || '-' }}</template>
          </el-table-column>
          <el-table-column label="通知方式" min-width="120">
            <template #default="{ row }">{{ formatNoticeType(row.notificateType) }}</template>
          </el-table-column>
          <el-table-column label="通知人员" min-width="150" show-overflow-tooltip>
            <template #default="{ row }">{{ formatPeople(row.notificatePeople) }}</template>
          </el-table-column>
          <el-table-column label="操作" width="150" fixed="right" align="center">
            <template #default="{ row }">
              <el-button type="primary" link @click="edit(row)">编辑</el-button>
              <el-button type="danger" link @click="remove(row)">删除</el-button>
            </template>
          </el-table-column>
        </el-table>

        <pagination
          v-show="total > 0"
          v-model:page="queryParams.page"
          v-model:limit="queryParams.pageSize"
          :total="total"
          @pagination="getRuleList"
        />
      </el-card>
    </template>

    <AddRule
      v-if="actionType === 'add'"
      :alarm-type-id="activeAlarmTypeId"
      @back="actionType = 'list'"
      @saved="getRuleList"
    />

    <EditRule
      v-if="actionType === 'edit'"
      :alarm-type-id="activeAlarmTypeId"
      :rule-id="currentRuleId"
      @back="actionType = 'list'"
      @saved="getRuleList"
    />

    <EditDeviceRule
      v-if="actionType === 'editDevice'"
      :alarm-type-id="activeAlarmTypeId"
      :selected-rows="selectedRows"
      @back="actionType = 'list'"
      @saved="getRuleList"
    />
  </div>
</template>

<script setup>
import { computed, reactive, ref, watch } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { listCategory } from '@/api/ai/category'
import { batchDeleteRule, deleteRule, listRule } from '@/api/ai/rule'
import { NOTIFICATE_TYPE_OPTIONS, normalizeList } from '../utils'
import AddRule from './components/AddRule.vue'
import EditDeviceRule from './components/EditDeviceRule.vue'
import EditRule from './components/EditRule.vue'

const props = defineProps({
  alarmTypeId: {
    type: [String, Number],
    default: undefined
  },
  title: {
    type: String,
    default: ''
  }
})

const loading = ref(false)
const deleteLoading = ref(false)
const categories = ref([])
const activeAlarmTypeId = ref('')
const actionType = ref('list')
const tableData = ref([])
const total = ref(0)
const selectedRows = ref([])
const currentRuleId = ref()
const queryParams = reactive({
  page: 1,
  pageSize: 10,
  query: undefined,
  alarmTypeId: undefined
})

const activeCategory = computed(() => categories.value.find((item) => String(item.alarmTypeId || item.id) === String(activeAlarmTypeId.value)))

watch(activeAlarmTypeId, (value) => {
  queryParams.alarmTypeId = value
})

function getCategories() {
  if (props.alarmTypeId) {
    categories.value = [{
      alarmTypeId: props.alarmTypeId,
      alarmTypeName: props.title || '算法配置'
    }]
    activeAlarmTypeId.value = String(props.alarmTypeId)
    getRuleList()
    return
  }

  listCategory({
    page: 1,
    pageSize: 1000
  }).then((res) => {
    const data = normalizeList(res)
    categories.value = data.list.filter((item) => item.isUse === 1)
    if (!activeAlarmTypeId.value && categories.value.length) {
      activeAlarmTypeId.value = String(categories.value[0].alarmTypeId || categories.value[0].id)
    }
    if (activeAlarmTypeId.value) getRuleList()
  })
}

function getRuleList() {
  if (!activeAlarmTypeId.value) return
  loading.value = true
  queryParams.alarmTypeId = activeAlarmTypeId.value
  listRule(queryParams).then((res) => {
    const data = normalizeList(res)
    tableData.value = data.list
    total.value = data.total
    selectedRows.value = []
  }).finally(() => {
    loading.value = false
  })
}

function changeCategory() {
  queryParams.page = 1
  queryParams.query = undefined
  getRuleList()
}

function handleQuery() {
  queryParams.page = 1
  getRuleList()
}

function resetQuery() {
  queryParams.query = undefined
  handleQuery()
}

function handleSelectionChange(selection) {
  selectedRows.value = selection
}

function edit(row) {
  currentRuleId.value = row.id
  actionType.value = 'edit'
}

function remove(row) {
  ElMessageBox.confirm('确定要删除该设备吗？', '提示', {
    type: 'warning'
  }).then(() => {
    deleteLoading.value = true
    deleteRule({ ruleId: row.id }).then(() => {
      ElMessage.success('删除规则成功')
      getRuleList()
    }).finally(() => {
      deleteLoading.value = false
    })
  }).catch(() => {})
}

function batchEdit() {
  if (selectedRows.value.length < 2) {
    ElMessage.warning('请至少选择2条要编辑的规则')
    return
  }
  ElMessageBox.confirm(`是否批量设置 ${selectedRows.value.length} 条规则？已选中的规则会被覆盖为新的规则。`, '批量设置', {
    type: 'warning'
  }).then(() => {
    actionType.value = 'editDevice'
  }).catch(() => {})
}

function batchRemove() {
  if (selectedRows.value.length < 2) {
    ElMessage.warning('请至少选择2条要删除的规则')
    return
  }
  ElMessageBox.confirm(`是否批量删除 ${selectedRows.value.length} 条规则？删除后不可恢复。`, '批量删除', {
    type: 'warning'
  }).then(() => {
    deleteLoading.value = true
    batchDeleteRule(selectedRows.value.map((item) => item.id)).then(() => {
      ElMessage.success('批量删除规则成功')
      getRuleList()
    }).finally(() => {
      deleteLoading.value = false
    })
  }).catch(() => {})
}

function firstDevice(row) {
  return Array.isArray(row.device) && row.device.length ? row.device[0] : null
}

function formatNoticeType(value) {
  if (!Array.isArray(value) || value.length === 0) return '无'
  return value.map((item) => NOTIFICATE_TYPE_OPTIONS.find((option) => option.value === item)?.label || item).join(',')
}

function formatPeople(value) {
  if (!Array.isArray(value) || value.length === 0) return '无'
  return value.map((item) => item.name).join(', ')
}

getCategories()
</script>

<style scoped>
.card-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
}
</style>
