// src/pages/ai/alarm/index.tsx
import { useMutation, useQuery } from '@tanstack/react-query';
import {
  Button,
  Card,
  Col,
  Form,
  Input,
  Row,
  Select,
  Space,
  DatePicker,
  Pagination,
  Tag,
  Empty,
  Checkbox,
  message as Message,
  Modal,
  message,
} from 'antd';
import { useMemo, useState } from 'react';
import { styled } from 'styled-components';

import aiService, { AlarmListReq } from '@/api/services/aiService';
import { useUserAiPermission } from '@/store/userStore';
import ProTag from '@/theme/antd/components/tag';

import AlarmDetailModal, { AlarmDetailModalProps } from './alarm-detail';

import type { CheckboxProps } from 'antd';

export default function AlarmPage() {
  const [searchForm] = Form.useForm();
  const aiPermissions = useUserAiPermission();
  const [queryParams, setQueryParams] = useState<AlarmListReq>({
    page: 1,
    pageSize: 8,
    status: undefined,
    deviceName: undefined,
    alarm_type_name: undefined,
    startTime: undefined,
    endTime: undefined,
  });
  const [alarmDetail, setAlarmDetail] = useState<AlarmDetailModalProps>({
    show: false,
    alarmItem: undefined,
    close: () => {
      setAlarmDetail((prev) => ({ ...prev, show: false, alarmItem: undefined }));
      refetch();
    },
  });

  const [checkedList, setCheckedList] = useState<number[]>([]);
  const [showCheckBox, setShowCheckBox] = useState(false);
  const [showBacthModal, setShowBacthModal] = useState(false);

  const { data, isLoading, refetch } = useQuery({
    queryKey: ['alarmList', queryParams],
    queryFn: () => aiService.getAlarmList(queryParams),
    onSuccess: (_data) => {
      setCheckedList([]);
    },
  });

  const categoryOptions = useMemo(() => {
    const enabled = (aiPermissions || []).filter((item) => item.status);
    return Array.from(new Set(enabled.map((item) => item.alarmTypeName)));
  }, [aiPermissions]);

  const { mutate } = useMutation(aiService.BatchUpdateAlarmStatus, {
    onSuccess: () => {
      message.success('操作成功');
      // 直接修改缓存的数据状态，减少重复请求
      refetch();
      setShowBacthModal(false);
      setCheckedList([]);
    },
    onError: () => {
      message.success('操作失败');
    },
  });

  const statusList = data?.list.filter((item) => item.status === 0) || [];

  const checkAll = statusList.length !== 0 && checkedList.length === statusList.length;
  const indeterminate = checkedList.length > 0 && !checkAll;

  const onSearchFormReset = () => {
    searchForm.resetFields();
  };

  const onSearchFormSubmit = () => {
    setQueryParams((prev) => {
      const { date, ...other } = searchForm.getFieldsValue();
      prev.startTime = date ? `${date[0].format('YYYY-MM-DD')} 00:00:00` : undefined;
      prev.endTime = date ? `${date[1].format('YYYY-MM-DD')} 23:59:59` : undefined;
      return { ...prev, ...other };
    });
  };

  const pageChange = (page: number, pageSize: number) => {
    setQueryParams({ ...queryParams, page, pageSize });
  };

  const onCheckListChange = (list: number[]) => {
    setCheckedList(list);
  };

  const handleCheckAll: CheckboxProps['onChange'] = (e) => {
    const { checked } = e.target;
    const list = data?.list.filter((item) => item.status === 0).map((item) => item.id) || [];
    setCheckedList(checked ? list : []);
  };

  const handleAlarm = (status: number) => {
    mutate({ alarmIds: checkedList, status });
  };

  const batchHandle = () => {
    if (checkedList.length === 0) {
      Message.error('请至少选择一个告警事件');
      return;
    }
    setShowBacthModal(true);
  };

  return (
    <Space direction="vertical" size="large" className="w-full">
      <Card>
        <Form form={searchForm}>
          <Row gutter={[16, 16]}>
            <Col span={24} lg={6}>
              <Form.Item<AlarmListReq> label="设备名称" name="deviceName" className="!mb-0">
                <Input placeholder="请输入设备名称" allowClear />
              </Form.Item>
            </Col>
            <Col span={24} lg={4}>
              <Form.Item<AlarmListReq> label="状态" name="status" className="!mb-0">
                <Select allowClear>
                  <Select.Option value="0">
                    <ProTag color="error">未处理</ProTag>
                  </Select.Option>
                  <Select.Option value="1">
                    <ProTag color="success">已处理</ProTag>
                  </Select.Option>
                  <Select.Option value="2">
                    <ProTag color="warning">误报</ProTag>
                  </Select.Option>
                </Select>
              </Form.Item>
            </Col>
            <Col span={24} lg={4}>
              <Form.Item<AlarmListReq> label="告警类型" name="alarm_type_name" className="!mb-0">
                <Select allowClear disabled={categoryOptions.length === 0}>
                  {categoryOptions.map((name) => {
                    return (
                      <Select.Option value={name} key={name}>
                        {name}
                      </Select.Option>
                    );
                  })}
                </Select>
              </Form.Item>
            </Col>
            <Col span={24} lg={6}>
              <Form.Item name="date" label="日期">
                <DatePicker.RangePicker format="YYYY-MM-DD" allowClear />
              </Form.Item>
            </Col>
            <Col span={24} lg={4}>
              <div className="flex justify-end">
                <Button onClick={onSearchFormReset}>重置</Button>
                <Button type="primary" className="ml-4" onClick={onSearchFormSubmit}>
                  搜索
                </Button>
              </div>
            </Col>
          </Row>
        </Form>
      </Card>
      <Card
        title="告警列表"
        loading={isLoading}
        extra={
          <Space>
            {showCheckBox ? (
              <>
                <Checkbox
                  onChange={handleCheckAll}
                  disabled={statusList.length === 0}
                  checked={checkAll}
                  indeterminate={indeterminate}
                >
                  全选
                </Checkbox>
                <Button type="default" onClick={batchHandle} disabled={checkedList.length === 0}>
                  批量处理
                </Button>
                <Button type="primary" onClick={() => setShowCheckBox(false)}>
                  取消
                </Button>
              </>
            ) : (
              <Button type="primary" onClick={() => setShowCheckBox(true)}>
                编辑
              </Button>
            )}
          </Space>
        }
      >
        {data?.list && data.list.length > 0 ? (
          <Checkbox.Group onChange={onCheckListChange} value={checkedList}>
            <Row gutter={[16, 16]} className="mb-4 min-h-96">
              {data?.list.map((alarmItem) => {
                return (
                  <Col lg={6} md={12} span={24} key={alarmItem.id}>
                    <StyledCardContent>
                      {showCheckBox && alarmItem.status === 0 && (
                        <div className="absolute left-1 top-1 z-10">
                          <Checkbox value={alarmItem.id} />
                        </div>
                      )}
                      <Card
                        className="w-full"
                        hoverable
                        cover={
                          <img
                            alt="example"
                            src={alarmItem.alarmImg}
                            style={{ height: '200px', background: '#000' }}
                          />
                        }
                        onClick={() => {
                          setAlarmDetail((prev) => ({ ...prev, show: true, alarmItem }));
                        }}
                      >
                        <div className="p-2">
                          <div className="mb-1 truncate font-bold ">
                            {alarmItem.deviceName || '测试-华为枪机测试-华为枪机'}
                          </div>
                          <p className="mb-1 text-sm">{`告警ID:${alarmItem.id}`}</p>
                          <p className="mb-1 text-sm text-gray-500">{alarmItem.createTime}</p>
                          <div>
                            <Tag color="blue">{alarmItem.modelname}</Tag>
                            <ProTag color={['error', 'success', 'warning'][alarmItem.status]}>
                              {['未处理', '已处理', '误报'][alarmItem.status]}
                            </ProTag>
                          </div>
                        </div>
                      </Card>
                    </StyledCardContent>
                  </Col>
                );
              })}

              <Col span={24}>
                <Pagination
                  defaultPageSize={queryParams.pageSize}
                  current={queryParams.page}
                  total={data?.total}
                  onChange={pageChange}
                  pageSizeOptions={[8, 20, 40, 100]}
                />
              </Col>
            </Row>
          </Checkbox.Group>
        ) : (
          <Empty image={Empty.PRESENTED_IMAGE_SIMPLE} />
        )}
      </Card>

      <AlarmDetailModal {...alarmDetail} />
      <Modal
        title="批量处理"
        footer={(_, { CancelBtn }) => (
          <>
            <CancelBtn />
            <Button type="primary" danger onClick={() => handleAlarm(2)}>
              误报
            </Button>
            <Button type="primary" onClick={() => handleAlarm(1)}>
              处理
            </Button>
          </>
        )}
        open={showBacthModal}
        onCancel={() => setShowBacthModal(false)}
      >
        <p>
          是否批量处理<span className="font-bold text-error">{checkedList.length}</span>
          条告警事件？
        </p>
        <p>告警ID为：{checkedList.join(', ')}</p>
      </Modal>
    </Space>
  );
}

const StyledCardContent = styled.div`
  position: relative;
  .ant-card {
    .ant-card-body {
      padding: 0px;
    }
  }
`;

// aivideo-gat1400/src/views/ai/alarm/index.vue
<template>
  <div class="app-container ai-alarm-page">
    <el-form :model="queryParams" ref="queryRef" :inline="true" v-show="showSearch" label-width="78px">
      <el-form-item label="设备名称" prop="deviceName">
        <el-input
          v-model="queryParams.deviceName"
          placeholder="请输入设备名称"
          clearable
          style="width: 220px"
          @keyup.enter="handleQuery"
        />
      </el-form-item>
      <el-form-item label="状态" prop="status">
        <el-select v-model="queryParams.status" clearable placeholder="请选择状态" style="width: 150px">
          <el-option v-for="item in ALARM_STATUS_OPTIONS" :key="item.value" :label="item.label" :value="item.value" />
        </el-select>
      </el-form-item>
      <el-form-item label="告警类型" prop="alarm_type_name">
        <el-select
          v-model="queryParams.alarm_type_name"
          clearable
          filterable
          placeholder="请选择告警类型"
          style="width: 180px"
        >
          <el-option v-for="item in categoryOptions" :key="item" :label="item" :value="item" />
        </el-select>
      </el-form-item>
      <el-form-item label="日期">
        <el-date-picker
          v-model="dateRange"
          type="daterange"
          range-separator="至"
          start-placeholder="开始日期"
          end-placeholder="结束日期"
          value-format="YYYY-MM-DD"
          style="width: 260px"
        />
      </el-form-item>
      <el-form-item>
        <el-button type="primary" icon="Search" @click="handleQuery">搜索</el-button>
        <el-button icon="Refresh" @click="resetQuery">重置</el-button>
      </el-form-item>
    </el-form>

    <el-card shadow="never">
      <template #header>
        <div class="card-header">
          <span>告警列表</span>
          <el-space>
            <template v-if="showCheckBox">
              <el-checkbox
                :model-value="checkAll"
                :indeterminate="indeterminate"
                :disabled="untreatedList.length === 0"
                @change="handleCheckAll"
              >
                全选
              </el-checkbox>
              <el-button :disabled="checkedList.length === 0" @click="batchVisible = true">批量处理</el-button>
              <el-button type="primary" @click="cancelBatch">取消</el-button>
            </template>
            <el-button v-else type="primary" @click="showCheckBox = true">编辑</el-button>
            <right-toolbar v-model:showSearch="showSearch" @queryTable="getList" />
          </el-space>
        </div>
      </template>

      <div v-loading="loading" min-height="420px">
        <el-empty v-if="tableData.length === 0" description="暂无告警" />
        <el-checkbox-group v-else v-model="checkedList">
          <el-row :gutter="16">
            <el-col v-for="item in tableData" :key="item.id" :xs="24" :sm="12" :lg="6" class="alarm-col">
              <div class="alarm-card-wrap">
                <el-checkbox
                  v-if="showCheckBox && item.status === 0"
                  class="alarm-checkbox"
                  :label="item.id"
                >
                  &nbsp;
                </el-checkbox>
                <el-card shadow="hover" class="alarm-card" @click="openDetail(item)">
                  <img :src="toImageUrl(item.alarmImg)" class="alarm-image" />
                  <div class="alarm-body">
                    <div class="alarm-title" :title="item.deviceName">{{ item.deviceName || '-' }}</div>
                    <div class="alarm-meta">告警ID：{{ item.id }}</div>
                    <div class="alarm-meta">{{ item.createTime || item.alarmTime }}</div>
                    <div class="alarm-tags">
                      <el-tag>{{ item.modelname || '-' }}</el-tag>
                      <el-tag :type="getStatusOption(item.status).type">{{ getStatusOption(item.status).label }}</el-tag>
                    </div>
                  </div>
                </el-card>
              </div>
            </el-col>
          </el-row>
        </el-checkbox-group>
      </div>

      <pagination
        v-show="total > 0"
        v-model:page="queryParams.page"
        v-model:limit="queryParams.pageSize"
        :total="total"
        :page-sizes="[8, 20, 40, 100]"
        @pagination="getList"
      />
    </el-card>

    <AlarmDetailDialog v-model="detailVisible" :alarm-item="currentAlarm" @handled="getList" />

    <el-dialog v-model="batchVisible" title="批量处理" width="520px">
      <p>是否批量处理 <strong class="danger-text">{{ checkedList.length }}</strong> 条告警事件？</p>
      <p>告警ID为：{{ checkedList.join(', ') }}</p>
      <template #footer>
        <el-button @click="batchVisible = false">取消</el-button>
        <el-button type="warning" :loading="batchLoading" @click="batchHandle(2)">误报</el-button>
        <el-button type="primary" :loading="batchLoading" @click="batchHandle(1)">处理</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup>
import { computed, reactive, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { batchHandleAlarm, listAlarm } from '@/api/ai/alarm'
import { listCategory } from '@/api/ai/category'
import { ALARM_STATUS_OPTIONS, normalizeList, toImageUrl } from '../utils'
import AlarmDetailDialog from './components/AlarmDetailDialog.vue'

const queryRef = ref()
const showSearch = ref(true)
const showCheckBox = ref(false)
const loading = ref(false)
const batchLoading = ref(false)
const batchVisible = ref(false)
const detailVisible = ref(false)
const tableData = ref([])
const total = ref(0)
const checkedList = ref([])
const currentAlarm = ref()
const dateRange = ref([])
const categoryOptions = ref([])
const queryParams = reactive({
  page: 1,
  pageSize: 8,
  status: undefined,
  deviceName: undefined,
  alarm_type_name: undefined,
  startTime: undefined,
  endTime: undefined
})

const untreatedList = computed(() => tableData.value.filter((item) => item.status === 0))
const checkAll = computed(() => untreatedList.value.length > 0 && checkedList.value.length === untreatedList.value.length)
const indeterminate = computed(() => checkedList.value.length > 0 && !checkAll.value)

function getList() {
  loading.value = true
  listAlarm(queryParams).then((res) => {
    const data = normalizeList(res)
    tableData.value = data.list
    total.value = data.total
    checkedList.value = []
  }).finally(() => {
    loading.value = false
  })
}

function getCategories() {
  listCategory({
    page: 1,
    pageSize: 1000
  }).then((res) => {
    const data = normalizeList(res)
    categoryOptions.value = [...new Set(data.list.filter((item) => item.isUse === 1).map((item) => item.alarmTypeName))]
  })
}

function handleQuery() {
  queryParams.page = 1
  if (Array.isArray(dateRange.value) && dateRange.value.length === 2) {
    queryParams.startTime = `${dateRange.value[0]} 00:00:00`
    queryParams.endTime = `${dateRange.value[1]} 23:59:59`
  } else {
    queryParams.startTime = undefined
    queryParams.endTime = undefined
  }
  getList()
}

function resetQuery() {
  queryRef.value?.resetFields()
  dateRange.value = []
  queryParams.startTime = undefined
  queryParams.endTime = undefined
  handleQuery()
}

function handleCheckAll(checked) {
  checkedList.value = checked ? untreatedList.value.map((item) => item.id) : []
}

function cancelBatch() {
  showCheckBox.value = false
  checkedList.value = []
}

function openDetail(item) {
  if (showCheckBox.value) return
  currentAlarm.value = item
  detailVisible.value = true
}

function batchHandle(status) {
  if (checkedList.value.length === 0) {
    ElMessage.warning('请至少选择一个告警事件')
    return
  }
  batchLoading.value = true
  batchHandleAlarm({
    alarmIds: checkedList.value,
    status
  }).then(() => {
    ElMessage.success('操作成功')
    batchVisible.value = false
    showCheckBox.value = false
    getList()
  }).finally(() => {
    batchLoading.value = false
  })
}

function getStatusOption(status) {
  return ALARM_STATUS_OPTIONS.find((item) => item.value === Number(status)) || ALARM_STATUS_OPTIONS[0]
}

getCategories()
getList()
</script>

<style scoped>
.card-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
}

.alarm-col {
  margin-bottom: 16px;
}

.alarm-card-wrap {
  position: relative;
}

.alarm-checkbox {
  position: absolute;
  left: 8px;
  top: 8px;
  z-index: 2;
}

.alarm-card {
  cursor: pointer;
}

.alarm-card :deep(.el-card__body) {
  padding: 0;
}

.alarm-image {
  display: block;
  width: 100%;
  height: 200px;
  object-fit: cover;
  background: #000;
}

.alarm-body {
  padding: 10px;
}

.alarm-title {
  font-weight: 700;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  margin-bottom: 6px;
}

.alarm-meta {
  color: var(--el-text-color-secondary);
  font-size: 13px;
  margin-bottom: 6px;
}

.alarm-tags {
  display: flex;
  flex-wrap: wrap;
  gap: 6px;
}

.danger-text {
  color: var(--el-color-danger);
}
</style>
